//autogenerated:yes
//nolint:revive,lll
package mower_map

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type SetJsonMapSrvReq struct {
	msg.Package `ros:"mower_map"`
	Json        string
}

type SetJsonMapSrvRes struct {
	msg.Package `ros:"mower_map"`
	Success     bool
	Message     string
}

type SetJsonMapSrv struct {
	msg.Package `ros:"mower_map"`
	SetJsonMapSrvReq
	SetJsonMapSrvRes
}
